"""empty message

Revision ID: 1ed8d7ab9089
Revises: 7d36209b66cc
Create Date: 2023-04-08 19:31:32.524932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed8d7ab9089'
down_revision = '7d36209b66cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characters', sa.String(length=120), nullable=False),
    sa.Column('planets', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['characters'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planets'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('characters')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
